export interface ModuleField { name: string; type: string; required?: boolean }

export const fieldConfigs: Record<string, ModuleField[]> = {
  accounts: [
    { name: 'accountName', type: 'text', required: true },
    { name: 'accountNo', type: 'text' },
    { name: 'parentId', type: 'text' },
    { name: 'website', type: 'text' },
    { name: 'phone', type: 'text' },
    { name: 'otherPhone', type: 'text' },
    { name: 'fax', type: 'text' },
    { name: 'email', type: 'email' },
    { name: 'email2', type: 'email' },
    { name: 'emailOptOut', type: 'checkbox' },
    { name: 'notifyOwner', type: 'checkbox' },
    { name: 'industry', type: 'select' },
    { name: 'accountType', type: 'select' },
    { name: 'ownership', type: 'select' },
    { name: 'rating', type: 'select' },
    { name: 'sicCode', type: 'text' },
    { name: 'tickerSymbol', type: 'text' },
    { name: 'glAccount', type: 'text' },
    { name: 'annualRevenue', type: 'number' },
    { name: 'employees', type: 'number' },
    { name: 'description', type: 'textarea' },
    { name: 'billingStreet', type: 'text' },
    { name: 'billingCity', type: 'text' },
    { name: 'billingState', type: 'text' },
    { name: 'billingCountry', type: 'text' },
    { name: 'billingPostalCode', type: 'text' },
    { name: 'billingPoBox', type: 'text' },
    { name: 'shippingStreet', type: 'text' },
    { name: 'shippingCity', type: 'text' },
    { name: 'shippingState', type: 'text' },
    { name: 'shippingCountry', type: 'text' },
    { name: 'shippingPostalCode', type: 'text' },
    { name: 'shippingPoBox', type: 'text' },
  ],
  contacts: [
    { name: 'salutation', type: 'select' },
    { name: 'firstName', type: 'text', required: true },
    { name: 'lastName', type: 'text', required: true },
    { name: 'accountId', type: 'account-select' },
    { name: 'email', type: 'email' },
    { name: 'secondaryEmail', type: 'email' },
    { name: 'phone', type: 'text' },
    { name: 'mobile', type: 'text' },
    { name: 'homePhone', type: 'text' },
    { name: 'otherPhone', type: 'text' },
    { name: 'fax', type: 'text' },
    { name: 'title', type: 'text' },
    { name: 'department', type: 'text' },
    { name: 'assistant', type: 'text' },
    { name: 'assistantPhone', type: 'text' },
    { name: 'dob', type: 'date' },
    { name: 'reportsTo', type: 'contact-select' },
    { name: 'leadSource', type: 'select' },
    { name: 'doNotCall', type: 'checkbox' },
    { name: 'emailOptOut', type: 'checkbox' },
    { name: 'notifyOwner', type: 'checkbox' },
    { name: 'image', type: 'image' },
    { name: 'portal', type: 'checkbox' },
    { name: 'description', type: 'textarea' },
    { name: 'mailingStreet', type: 'text' },
    { name: 'mailingCity', type: 'text' },
    { name: 'mailingState', type: 'text' },
    { name: 'mailingCountry', type: 'text' },
    { name: 'mailingPostalCode', type: 'text' },
    { name: 'mailingPoBox', type: 'text' },
    { name: 'otherStreet', type: 'text' },
    { name: 'otherCity', type: 'text' },
    { name: 'otherState', type: 'text' },
    { name: 'otherCountry', type: 'text' },
    { name: 'otherPostalCode', type: 'text' },
    { name: 'otherPoBox', type: 'text' },
  ],
  leads: [
    { name: 'salutation', type: 'select' },
    { name: 'firstName', type: 'text', required: true },
    { name: 'lastName', type: 'text', required: true },
    { name: 'company', type: 'text', required: true },
    { name: 'assignedTo', type: 'user-select', required: true },
    { name: 'title', type: 'text' },
    { name: 'email', type: 'email' },
    { name: 'secondaryEmail', type: 'email' },
    { name: 'phone', type: 'text' },
    { name: 'mobile', type: 'text' },
    { name: 'fax', type: 'text' },
    { name: 'website', type: 'text' },
    { name: 'leadSource', type: 'select' },
    { name: 'leadStatus', type: 'select' },
    { name: 'industry', type: 'select' },
    { name: 'annualRevenue', type: 'number' },
    { name: 'noOfEmployees', type: 'number' },
    { name: 'rating', type: 'text' },
    { name: 'interest', type: 'text' },
    { name: 'description', type: 'textarea' },
    { name: 'street', type: 'text' },
    { name: 'city', type: 'text' },
    { name: 'state', type: 'text' },
    { name: 'country', type: 'text' },
    { name: 'postalCode', type: 'text' },
    { name: 'poBox', type: 'text' },
  ],
  potentials: [
    { name: 'potentialName', type: 'text', required: true },
    { name: 'amount', type: 'number' },
    { name: 'currency', type: 'currency-select' },
    { name: 'closingDate', type: 'date', required: true },
    { name: 'stage', type: 'select', required: true },
    { name: 'probability', type: 'number' },
    { name: 'type', type: 'select' },
    { name: 'leadSource', type: 'select' },
    { name: 'forecastCategory', type: 'select' },
    { name: 'outcomeAnalysis', type: 'text' },
    { name: 'nextStep', type: 'text' },
    { name: 'description', type: 'textarea' },
  ],
  competitors: [
    { name: 'competitorName', type: 'text', required: true },
    { name: 'website', type: 'url' },
    { name: 'strengths', type: 'textarea' },
    { name: 'weaknesses', type: 'textarea' },
    { name: 'products', type: 'textarea' },
    { name: 'marketShare', type: 'number' },
    { name: 'rating', type: 'select' },
    { name: 'description', type: 'textarea' },
  ],
  tickets: [
    { name: 'title', type: 'text', required: true },
    { name: 'contactId', type: 'contact-select' },
    { name: 'accountId', type: 'account-select' },
    { name: 'productId', type: 'product-select' },
    { name: 'description', type: 'textarea' },
    { name: 'status', type: 'select' },
    { name: 'priority', type: 'select' },
    { name: 'severity', type: 'select' },
    { name: 'category', type: 'select' },
    { name: 'solution', type: 'textarea' },
    { name: 'updateLog', type: 'textarea' },
    { name: 'hours', type: 'number' },
    { name: 'days', type: 'number' },
    { name: 'fromMail', type: 'email' },
    { name: 'versionId', type: 'text' },
  ],
  products: [
    { name: 'productNo', type: 'text' },
    { name: 'productName', type: 'text', required: true },
    { name: 'image', type: 'image' },
    { name: 'productCategory', type: 'search-select' },
    { name: 'manufacturer', type: 'search-select' },
    { name: 'glAccount', type: 'search-select' },
    { name: 'usageUnit', type: 'search-select' },
    { name: 'taxClass', type: 'search-select' },
    { name: 'isActive', type: 'checkbox' },
    { name: 'vat', type: 'checkbox' },
    { name: 'isService', type: 'checkbox' },
    { name: 'isSales', type: 'checkbox' },
    { name: 'serialNo', type: 'text' },
    { name: 'mfrPartNo', type: 'text' },
    { name: 'vendorPartNo', type: 'text' },
    { name: 'productSheet', type: 'text' },
    { name: 'qtyPerUnit', type: 'text' },
    { name: 'website', type: 'text' },
    { name: 'unitPrice', type: 'number' },
    { name: 'costPrice', type: 'number' },
    { name: 'commissionRate', type: 'number' },
    { name: 'commissionMethod', type: 'search-select' },
    { name: 'qtyInStock', type: 'number' },
    { name: 'reorderLevel', type: 'number' },
    { name: 'qtyOnOrder', type: 'number' },
    { name: 'qtyInDemand', type: 'number' },
    { name: 'weight', type: 'number' },
    { name: 'packSize', type: 'number' },
    { name: 'vendorId', type: 'vendor-select' },
    { name: 'assignedTo', type: 'user-select' },
    { name: 'description', type: 'textarea' },
  ],
  projects: [
    { name: 'projectName', type: 'text', required: true },
    { name: 'projectNo', type: 'text' },
    { name: 'projectType', type: 'select' },
    { name: 'status', type: 'select' },
    { name: 'priority', type: 'select' },
    { name: 'progress', type: 'number' },
    { name: 'accountId', type: 'account-select' },
    { name: 'contactId', type: 'contact-select' },
    { name: 'assignedTo', type: 'user-select' },
    { name: 'startDate', type: 'date' },
    { name: 'endDate', type: 'date' },
    { name: 'actualEndDate', type: 'date' },
    { name: 'targetBudget', type: 'number' },
    { name: 'actualBudget', type: 'number' },
    { name: 'url', type: 'text' },
    { name: 'description', type: 'textarea' },
  ],
  campaigns: [
    { name: 'campaignName', type: 'text', required: true },
    { name: 'campaignType', type: 'select' },
    { name: 'status', type: 'select' },
    { name: 'startDate', type: 'date' },
    { name: 'endDate', type: 'date' },
    { name: 'closingDate', type: 'date' },
    { name: 'expectedRevenue', type: 'number' },
    { name: 'budget', type: 'number' },
    { name: 'actualCost', type: 'number' },
    { name: 'expectedResponse', type: 'number' },
    { name: 'targetSize', type: 'number' },
    { name: 'sponsor', type: 'text' },
    { name: 'targetAudience', type: 'text' },
    { name: 'expectedROI', type: 'number' },
    { name: 'actualROI', type: 'number' },
    { name: 'expectedResponseCount', type: 'number' },
    { name: 'expectedSalesCount', type: 'number' },
    { name: 'actualResponseCount', type: 'number' },
    { name: 'actualSalesCount', type: 'number' },
    { name: 'description', type: 'textarea' },
  ],
  invoices: [
    { name: 'subject', type: 'text', required: true },
    { name: 'invoiceNo', type: 'text' },
    { name: 'invoiceDate', type: 'date' },
    { name: 'dueDate', type: 'date' },
    { name: 'grandTotal', type: 'number' },
    { name: 'subTotal', type: 'number' },
    { name: 'discount', type: 'number' },
    { name: 'discountPercent', type: 'number' },
    { name: 'adjustment', type: 'number' },
    { name: 'shipping', type: 'number' },
    { name: 'shippingHandling', type: 'number' },
    { name: 'taxAmount', type: 'number' },
    { name: 'total', type: 'number' },
    { name: 'salesCommission', type: 'number' },
    { name: 'exciseDuty', type: 'number' },
    { name: 'customerNo', type: 'text' },
    { name: 'purchaseOrderNo', type: 'text' },
    { name: 'invoiceStatus', type: 'select' },
    { name: 'taxType', type: 'select' },
    { name: 'currency', type: 'currency-select' },
    { name: 'conversionRate', type: 'number' },
    { name: 'notes', type: 'textarea' },
    { name: 'terms', type: 'textarea' },
    { name: 'description', type: 'textarea' },
    { name: 'billingStreet', type: 'text' },
    { name: 'billingCity', type: 'text' },
    { name: 'billingState', type: 'text' },
    { name: 'billingCountry', type: 'text' },
    { name: 'billingPostalCode', type: 'text' },
    { name: 'billingPoBox', type: 'text' },
    { name: 'shippingStreet', type: 'text' },
    { name: 'shippingCity', type: 'text' },
    { name: 'shippingState', type: 'text' },
    { name: 'shippingCountry', type: 'text' },
    { name: 'shippingPostalCode', type: 'text' },
    { name: 'shippingPoBox', type: 'text' },
  ],
  services: [
    { name: 'serviceName', type: 'text', required: true },
    { name: 'serviceNo', type: 'text' },
    { name: 'serviceCategory', type: 'select' },
    { name: 'unitPrice', type: 'number' },
    { name: 'costPrice', type: 'number' },
    { name: 'commissionRate', type: 'number' },
    { name: 'commissionMethod', type: 'select' },
    { name: 'usageUnit', type: 'select' },
    { name: 'reorderLevel', type: 'number' },
    { name: 'qtyInStock', type: 'number' },
    { name: 'qtyInDemand', type: 'number' },
    { name: 'website', type: 'text' },
    { name: 'serialNo', type: 'text' },
    { name: 'glAccount', type: 'text' },
    { name: 'taxClass', type: 'text' },
    { name: 'discontinued', type: 'checkbox' },
    { name: 'description', type: 'textarea' },
  ],
  vendors: [
    { name: 'vendorName', type: 'text', required: true },
    { name: 'email', type: 'email' },
    { name: 'phone', type: 'text' },
    { name: 'mobile', type: 'text' },
    { name: 'website', type: 'text' },
    { name: 'category', type: 'text' },
    { name: 'glAccount', type: 'select' },
    { name: 'description', type: 'textarea' },
    { name: 'street', type: 'text' },
    { name: 'city', type: 'text' },
    { name: 'state', type: 'text' },
    { name: 'country', type: 'text' },
    { name: 'postalCode', type: 'text' },
  ],
  pricebooks: [
    { name: 'priceBookName', type: 'text', required: true },
    { name: 'active', type: 'checkbox' },
    { name: 'description', type: 'textarea' },
  ],
  quotes: [
    { name: 'subject', type: 'text', required: true },
    { name: 'quoteNo', type: 'text' },
    { name: 'validUntil', type: 'date' },
    { name: 'grandTotal', type: 'number' },
    { name: 'subTotal', type: 'number' },
    { name: 'discount', type: 'number' },
    { name: 'discountPercent', type: 'number' },
    { name: 'adjustment', type: 'number' },
    { name: 'shipping', type: 'number' },
    { name: 'shippingHandling', type: 'number' },
    { name: 'taxAmount', type: 'number' },
    { name: 'total', type: 'number' },
    { name: 'carrier', type: 'select' },
    { name: 'inventoryManager', type: 'text' },
    { name: 'taxType', type: 'select' },
    { name: 'quoteStage', type: 'select' },
    { name: 'currency', type: 'currency-select' },
    { name: 'conversionRate', type: 'number' },
    { name: 'terms', type: 'textarea' },
    { name: 'description', type: 'textarea' },
    { name: 'billingStreet', type: 'text' },
    { name: 'billingCity', type: 'text' },
    { name: 'billingState', type: 'text' },
    { name: 'billingCountry', type: 'text' },
    { name: 'billingPostalCode', type: 'text' },
    { name: 'billingPoBox', type: 'text' },
    { name: 'shippingStreet', type: 'text' },
    { name: 'shippingCity', type: 'text' },
    { name: 'shippingState', type: 'text' },
    { name: 'shippingCountry', type: 'text' },
    { name: 'shippingPostalCode', type: 'text' },
    { name: 'shippingPoBox', type: 'text' },
  ],
  salesorders: [
    { name: 'subject', type: 'text', required: true },
    { name: 'salesOrderNo', type: 'text' },
    { name: 'validUntil', type: 'date' },
    { name: 'grandTotal', type: 'number' },
    { name: 'subTotal', type: 'number' },
    { name: 'discount', type: 'number' },
    { name: 'discountPercent', type: 'number' },
    { name: 'adjustment', type: 'number' },
    { name: 'shipping', type: 'number' },
    { name: 'shippingHandling', type: 'number' },
    { name: 'taxAmount', type: 'number' },
    { name: 'total', type: 'number' },
    { name: 'carrier', type: 'text' },
    { name: 'customerNo', type: 'text' },
    { name: 'purchaseOrderNo', type: 'text' },
    { name: 'salesCommission', type: 'number' },
    { name: 'exciseDuty', type: 'number' },
    { name: 'soStatus', type: 'select' },
    { name: 'taxType', type: 'select' },
    { name: 'carrier', type: 'select' },
    { name: 'currency', type: 'currency-select' },
    { name: 'conversionRate', type: 'number' },
    { name: 'terms', type: 'textarea' },
    { name: 'description', type: 'textarea' },
    { name: 'billingStreet', type: 'text' },
    { name: 'billingCity', type: 'text' },
    { name: 'billingState', type: 'text' },
    { name: 'billingCountry', type: 'text' },
    { name: 'billingPostalCode', type: 'text' },
    { name: 'billingPoBox', type: 'text' },
    { name: 'shippingStreet', type: 'text' },
    { name: 'shippingCity', type: 'text' },
    { name: 'shippingState', type: 'text' },
    { name: 'shippingCountry', type: 'text' },
    { name: 'shippingPostalCode', type: 'text' },
    { name: 'shippingPoBox', type: 'text' },
  ],
  purchaseorders: [
    { name: 'subject', type: 'text', required: true },
    { name: 'purchaseOrderNo', type: 'text' },
    { name: 'validUntil', type: 'date' },
    { name: 'grandTotal', type: 'number' },
    { name: 'subTotal', type: 'number' },
    { name: 'discount', type: 'number' },
    { name: 'discountPercent', type: 'number' },
    { name: 'adjustment', type: 'number' },
    { name: 'shipping', type: 'number' },
    { name: 'shippingHandling', type: 'number' },
    { name: 'taxAmount', type: 'number' },
    { name: 'total', type: 'number' },
    { name: 'carrier', type: 'text' },
    { name: 'salesCommission', type: 'number' },
    { name: 'exciseDuty', type: 'number' },
    { name: 'poStatus', type: 'select' },
    { name: 'taxType', type: 'select' },
    { name: 'carrier', type: 'select' },
    { name: 'currency', type: 'currency-select' },
    { name: 'conversionRate', type: 'number' },
    { name: 'vendorId', type: 'vendor-select' },
    { name: 'contactId', type: 'contact-select' },
    { name: 'terms', type: 'textarea' },
    { name: 'description', type: 'textarea' },
    { name: 'billingStreet', type: 'text' },
    { name: 'billingCity', type: 'text' },
    { name: 'billingState', type: 'text' },
    { name: 'billingCountry', type: 'text' },
    { name: 'billingPostalCode', type: 'text' },
    { name: 'billingPoBox', type: 'text' },
    { name: 'shippingStreet', type: 'text' },
    { name: 'shippingCity', type: 'text' },
    { name: 'shippingState', type: 'text' },
    { name: 'shippingCountry', type: 'text' },
    { name: 'shippingPostalCode', type: 'text' },
    { name: 'shippingPoBox', type: 'text' },
  ],
  faq: [
    { name: 'title', type: 'text', required: true },
    { name: 'faqNo', type: 'text' },
    { name: 'category', type: 'select' },
    { name: 'status', type: 'select' },
    { name: 'assignedTo', type: 'user-select' },
    { name: 'description', type: 'textarea' },
    { name: 'answer', type: 'textarea' },
  ],
  documents: [
    { name: 'title', type: 'text', required: true },
    { name: 'fileName', type: 'file' },
    { name: 'fileType', type: 'select' },
    { name: 'fileLocationType', type: 'text' },
    { name: 'fileStatus', type: 'select' },
    { name: 'fileVersion', type: 'text' },
    { name: 'noteContent', type: 'textarea' },
    { name: 'folderId', type: 'text' },
  ],
  emails: [
    { name: 'subject', type: 'text' },
    { name: 'fromEmail', type: 'email' },
    { name: 'toEmails', type: 'text' },
    { name: 'ccEmails', type: 'text' },
    { name: 'bccEmails', type: 'text' },
    { name: 'emailFlag', type: 'select' },
    { name: 'parentId', type: 'text' },
    { name: 'parentModule', type: 'text' },
    { name: 'body', type: 'textarea' },
  ],
  emailtemplates: [
    { name: 'templateName', type: 'text', required: true },
    { name: 'subject', type: 'text', required: true },
    { name: 'module', type: 'text' },
    { name: 'folderName', type: 'text' },
    { name: 'body', type: 'textarea', required: true },
  ],
  projecttasks: [
    { name: 'projectId', type: 'project-select', required: true },
    { name: 'projectTaskNo', type: 'text' },
    { name: 'title', type: 'text', required: true },
    { name: 'status', type: 'select' },
    { name: 'priority', type: 'select' },
    { name: 'projectTaskType', type: 'select' },
    { name: 'progress', type: 'number' },
    { name: 'hours', type: 'number' },
    { name: 'assignedTo', type: 'user-select' },
    { name: 'startDate', type: 'date' },
    { name: 'endDate', type: 'date' },
    { name: 'description', type: 'textarea' },
  ],
  projectmilestones: [
    { name: 'projectId', type: 'project-select', required: true },
    { name: 'milestoneNo', type: 'text' },
    { name: 'title', type: 'text', required: true },
    { name: 'status', type: 'select' },
    { name: 'progress', type: 'number' },
    { name: 'milestoneDate', type: 'date' },
    { name: 'milestoneType', type: 'select' },
    { name: 'plannedHours', type: 'number' },
    { name: 'actualHours', type: 'number' },
    { name: 'sequence', type: 'number' },
    { name: 'assignedTo', type: 'user-select' },
    { name: 'startDate', type: 'date' },
    { name: 'endDate', type: 'date' },
    { name: 'description', type: 'textarea' },
  ],
  assets: [
    { name: 'assetName', type: 'text', required: true },
    { name: 'assetNo', type: 'text' },
    { name: 'serialNo', type: 'text' },
    { name: 'tagNumber', type: 'text' },
    { name: 'productId', type: 'product-select' },
    { name: 'accountId', type: 'account-select' },
    { name: 'contactId', type: 'contact-select' },
    { name: 'datesInService', type: 'date' },
    { name: 'dateOutOfService', type: 'date' },
    { name: 'dateSold', type: 'date' },
    { name: 'status', type: 'select' },
    { name: 'shippingMethod', type: 'text' },
    { name: 'shippingTrackingNumber', type: 'text' },
    { name: 'invoiceId', type: 'text' },
    { name: 'description', type: 'textarea' },
  ],
  servicecontracts: [
    { name: 'contractName', type: 'text', required: true },
    { name: 'contractNo', type: 'text' },
    { name: 'contractType', type: 'select' },
    { name: 'status', type: 'select' },
    { name: 'priority', type: 'select' },
    { name: 'accountId', type: 'account-select' },
    { name: 'contactId', type: 'contact-select' },
    { name: 'startDate', type: 'date' },
    { name: 'endDate', type: 'date' },
    { name: 'dueDate', type: 'date' },
    { name: 'renewalDate', type: 'date' },
    { name: 'progress', type: 'number' },
    { name: 'trackingUnit', type: 'select' },
    { name: 'totalUnits', type: 'number' },
    { name: 'usedUnits', type: 'number' },
    { name: 'unitPrice', type: 'number' },
    { name: 'costPrice', type: 'number' },
    { name: 'relatedTo', type: 'text' },
    { name: 'relatedModule', type: 'text' },
    { name: 'description', type: 'textarea' },
  ],
  smsnotifier: [
    { name: 'toNumber', type: 'text', required: true },
    { name: 'fromNumber', type: 'text' },
    { name: 'message', type: 'textarea' },
    { name: 'status', type: 'select' },
  ],
}
